# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\x12\x04room\"\x1f\n\x0bRoomRequest\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x05\"0\n\x0cRoomResponse\x12 \n\x05rooms\x18\x01 \x03(\x0b\x32\x11.room.RoomDetails\"d\n\x0bRoomDetails\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x02 \x01(\x05\x12\x0e\n\x06office\x18\x03 \x01(\t\x12\x12\n\nwhiteboard\x18\x04 \x01(\x08\x12\x11\n\tprojector\x18\x05 \x01(\x08\x32=\n\x04Room\x12\x35\n\ngetDetails\x12\x11.room.RoomRequest\x1a\x12.room.RoomResponse\"\x00\x62\x06proto3')



_ROOMREQUEST = DESCRIPTOR.message_types_by_name['RoomRequest']
_ROOMRESPONSE = DESCRIPTOR.message_types_by_name['RoomResponse']
_ROOMDETAILS = DESCRIPTOR.message_types_by_name['RoomDetails']
RoomRequest = _reflection.GeneratedProtocolMessageType('RoomRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOMREQUEST,
  '__module__' : 'room_pb2'
  # @@protoc_insertion_point(class_scope:room.RoomRequest)
  })
_sym_db.RegisterMessage(RoomRequest)

RoomResponse = _reflection.GeneratedProtocolMessageType('RoomResponse', (_message.Message,), {
  'DESCRIPTOR' : _ROOMRESPONSE,
  '__module__' : 'room_pb2'
  # @@protoc_insertion_point(class_scope:room.RoomResponse)
  })
_sym_db.RegisterMessage(RoomResponse)

RoomDetails = _reflection.GeneratedProtocolMessageType('RoomDetails', (_message.Message,), {
  'DESCRIPTOR' : _ROOMDETAILS,
  '__module__' : 'room_pb2'
  # @@protoc_insertion_point(class_scope:room.RoomDetails)
  })
_sym_db.RegisterMessage(RoomDetails)

_ROOM = DESCRIPTOR.services_by_name['Room']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOMREQUEST._serialized_start=20
  _ROOMREQUEST._serialized_end=51
  _ROOMRESPONSE._serialized_start=53
  _ROOMRESPONSE._serialized_end=101
  _ROOMDETAILS._serialized_start=103
  _ROOMDETAILS._serialized_end=203
  _ROOM._serialized_start=205
  _ROOM._serialized_end=266
# @@protoc_insertion_point(module_scope)
