# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import room_pb2 as room__pb2


class RoomStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDetails = channel.unary_unary(
                '/room.Room/getDetails',
                request_serializer=room__pb2.RoomRequest.SerializeToString,
                response_deserializer=room__pb2.RoomResponse.FromString,
                )


class RoomServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.getDetails,
                    request_deserializer=room__pb2.RoomRequest.FromString,
                    response_serializer=room__pb2.RoomResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'room.Room', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Room(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/room.Room/getDetails',
            room__pb2.RoomRequest.SerializeToString,
            room__pb2.RoomResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
